### PR TITLE
Bindmount /dev/zero into our root_dir

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @staticfloat @keno

**Review by Keno — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@staticfloat Can you remind me what the release process is for this repository?

Should I go ahead and bump the `Project.toml` version number as part of this PR?

**Comment by DilumAluthge** [comment]
I went ahead and bumped the `Project.toml` version number from `1.1.0` to `1.2.0`. But I can revert that change if need be.

**Comment by staticfloat** [comment]
Yeah, bumping version is fine, there's been a good amount of change recently.

**Pull request merged**
