### PR TITLE
Add the ability to use pre-built Docker images (e.g. from Docker Hub)

### LINKED ISSUE #21: Feature request: make it easy for users to generate their own rootfs images
Instead of building a Docker image locally, I would like to pull a Docker image from Docker Hub and use that.

For example, I would like to pull this image and use it:
- https://hub.docker.com/_/julia

Could we add this feature?

---

Feature request: make it easy for users to generate their own rootfs images (for example, by pulling an Docker image from Docker Hub and then converting that Docker image to a rootfs image)

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #21

### CODE REVIEW

**Comment by staticfloat** [comment]
I am kind of against diverging the Docker and UserNS executors; I would much rather make it easy for users to generate their own rootfs images (for example by stealing one from Docker Hub) than allow the Docker executor to gain features that aren't easy to replicate with the other executors.

Let me think through the best way to make this easy; clearly it would be great if we can cheaply and easily get rootfs images from Docker; but I'd like to do it in such a way that we can do it for the UserNS executor as well.

**Comment by DilumAluthge** [comment]
Sounds good! My use case is really just that I want to be able to have Julia pre-installed when I use the Docker executor. So any way that we can achieve that goal sounds good to me!

**Comment by DilumAluthge** [comment]
Would something like this work?

```bash
mkdir rootfs && docker export $(docker create julia) | tar -C rootfs -xvf -
```

**Comment by DilumAluthge** [comment]
I'm closing this PR in favor of this plan:

> make it easy for users to generate their own rootfs images (for example by stealing one from Docker Hub)

**Pull request closed without merging**
