### PR TITLE
Allow the `with_executor` function to take keyword arguments, which it will forward to the `executor_type` constructor

### PR DESCRIPTION
**Pull request by DilumAluthge**
This allows you to customize the construction of the `SandboxExecutor`.

For example:

```julia
with_executor(DockerExecutor; privileges = :no_new_privileges) do exe
    run(exe, config, `/bin/sh`)
end
```

### CODE REVIEW

**Comment by staticfloat** [comment]
This will easily lead to issues around e.g.

```
exe = preferred_executor()
with_executor(exe) do
    ...
end

# This breaks, because the `exe` object was cleaned up at the end of the previous `with_executor()`
with_executor(exe) do
    ...
end
```

I think instead we can provide `kwargs` to `with_executor()` and pass them through, if we really need the ability to customize the executor arguments.

**Comment by DilumAluthge** [comment]
> I think instead we can provide `kwargs` to `with_executor()` and pass them through, if we really need the ability to customize the executor arguments.

This sounds like a good idea!

**Comment by DilumAluthge** [comment]
> I think instead we can provide `kwargs` to `with_executor()` and pass them through, if we really need the ability to customize the executor arguments.

Okay, I have now modified this PR to implement your suggestion.

**Comment by DilumAluthge** [comment]
I'm pretty sure that the test failures are unrelated. But it would be good to fix the test failures on master, and then rebase this PR on master, before merging.

**Comment by DilumAluthge** [comment]
@staticfloat Any idea why these tests are failing?

**Comment by DilumAluthge** [comment]
Okay, passing now.

**Pull request merged**
