### PR TITLE
Require UserNSSandbox_jll `v2022.1.6`

### PR DESCRIPTION
**Pull request by staticfloat**
This is the first version to provide the `--hostname` option.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Debian mirror issue?

**Comment by staticfloat** [comment]
Hmmm, now Codecov is giving me an error:

```
ErrorDetail(string='Your CI provider is not compatible with tokenless uploads, please upload using your repository token to resolve this.', code='not_found')
```

**Comment by DilumAluthge** [comment]
On Buildkite? I would just skip Codecov uploads on Buildkite. Unless you want to set up cryptic on this repo, and then add a Codecov token as a secret.

**Comment by staticfloat** [comment]
Top hit: https://community.codecov.com/t/buildkite-token-less-upload/2259

hah.  Okay, yeah, I'll just disable for now.

**Comment by giordano** [comment]
Any clue what's up in nightly?
```
        Info Packages marked with ⌅ have new versions available but cannot be upgraded. To see why use `status --outdated`
     Testing Sandbox
      Status `/tmp/jl_qooGdW/Project.toml`
  [9307e30f] Sandbox v1.1.0 `~/work/Sandbox.jl/Sandbox.jl`
  [6c6a2e73] Scratch v1.1.0
  [b88861f7] UserNSSandbox_jll v2022.1.6+0
  [4af54fe1] LazyArtifacts `@stdlib/LazyArtifacts`
  [44cfe95a] Pkg v1.8.0 `@stdlib/Pkg`
  [ea8e919c] SHA v0.7.0 `@stdlib/SHA`
  [8dfed614] Test `@stdlib/Test`
      Status `/tmp/jl_qooGdW/Manifest.toml`
ERROR: KeyError: key UUID("9b64493d-8859-5bf3-93d7-7c32dd38186f") not found
Stacktrace:
  [1] getindex
    @ ./dict.jl:498 [inlined]
  [2] status_compat_info(pkg::Pkg.Types.PackageSpec, env::Pkg.Types.EnvCache, regs::Vector{Pkg.Registry.RegistryInstance})
    @ Pkg.Operations /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1796
  [3] print_status(env::Pkg.Types.EnvCache, old_env::Nothing, registries::Vector{Pkg.Registry.RegistryInstance}, header::Symbol, uuids::Vector{Base.UUID}, names::Vector{String}; manifest::Bool, diff::Bool, ignore_indent::Bool, outdated::Bool, io::IOContext{Base.PipeEndpoint}, mode::Pkg.Types.PackageMode, hidden_upgrades_info::Bool)
    @ Pkg.Operations /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1911
  [4] status(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}; header::Nothing, mode::Pkg.Types.PackageMode, git_diff::Bool, env_diff::Nothing, ignore_indent::Bool, io::IOContext{Base.PipeEndpoint}, outdated::Bool, hidden_upgrades_info::Bool)
    @ Pkg.Operations /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:2056
  [5] (::Pkg.Operations.var"#110#112"{Bool, Cmd, Cmd, Nothing, Pkg.Types.Context, Vector{Tuple{String, Base.Process}}, String, Pkg.Types.PackageSpec})()
    @ Pkg.Operations /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1659
  [6] withenv(::Pkg.Operations.var"#110#112"{Bool, Cmd, Cmd, Nothing, Pkg.Types.Context, Vector{Tuple{String, Base.Process}}, String, Pkg.Types.PackageSpec}, ::Pair{String, String}, ::Vararg{Pair{String}})
    @ Base ./env.jl:172
  [7] (::Pkg.Operations.var"#100#104"{String, Bool, Bool, Bool, Pkg.Operations.var"#110#112"{Bool, Cmd, Cmd, Nothing, Pkg.Types.Context, Vector{Tuple{String, Base.Process}}, String, Pkg.Types.PackageSpec}, Pkg.Types.PackageSpec})()
    @ Pkg.Operations /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1540
  [8] with_temp_env(fn::Pkg.Operations.var"#100#104"{String, Bool, Bool, Bool, Pkg.Operations.var"#110#112"{Bool, Cmd, Cmd, Nothing, Pkg.Types.Context, Vector{Tuple{String, Base.Process}}, String, Pkg.Types.PackageSpec}, Pkg.Types.PackageSpec}, temp_env::String)
    @ Pkg.Operations /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1423
  [9] (::Pkg.Operations.var"#99#103"{Bool, Bool, Bool, Pkg.Operations.var"#110#112"{Bool, Cmd, Cmd, Nothing, Pkg.Types.Context, Vector{Tuple{String, Base.Process}}, String, Pkg.Types.PackageSpec}, Pkg.Types.Context, Pkg.Types.PackageSpec, String, Nothing, String})(tmp::String)
    @ Pkg.Operations /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1503
 [10] mktempdir(fn::Pkg.Operations.var"#99#103"{Bool, Bool, Bool, Pkg.Operations.var"#110#112"{Bool, Cmd, Cmd, Nothing, Pkg.Types.Context, Vector{Tuple{String, Base.Process}}, String, Pkg.Types.PackageSpec}, Pkg.Types.Context, Pkg.Types.PackageSpec, String, Nothing, String}, parent::String; prefix::String)
    @ Base.Filesystem ./file.jl:763
 [11] mktempdir(fn::Function, parent::String) (repeats 2 times)
    @ Base.Filesystem ./file.jl:761
 [12] sandbox(fn::Function, ctx::Pkg.Types.Context, target::Pkg.Types.PackageSpec, target_path::String, sandbox_path::String, sandbox_project_override::Nothing; force_latest_compatible_version::Bool, allow_earlier_backwards_compatible_versions::Bool, allow_reresolve::Bool)
    @ Pkg.Operations /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1469
 [13] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing, force_latest_compatible_version::Bool, allow_earlier_backwards_compatible_versions::Bool, allow_reresolve::Bool)
    @ Pkg.Operations /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1656
 [14] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, test_fn::Nothing, julia_args::Vector{String}, test_args::Cmd, force_latest_compatible_version::Bool, allow_earlier_backwards_compatible_versions::Bool, allow_reresolve::Bool, kwargs::Base.Pairs{Symbol, IOContext{Base.PipeEndpoint}, Tuple{Symbol}, NamedTuple{(:io,), Tuple{IOContext{Base.PipeEndpoint}}}})
    @ Pkg.API /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/API.jl:431
 [15] test(pkgs::Vector{Pkg.Types.PackageSpec}; io::IOContext{Base.PipeEndpoint}, kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:coverage, :julia_args, :force_latest_compatible_version), Tuple{Bool, Vector{String}, Bool}}})
    @ Pkg.API /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/API.jl:156
 [16] test(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:coverage, :julia_args, :force_latest_compatible_version), Tuple{Bool, Vector{String}, Bool}}})
    @ Pkg.API /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/Pkg/src/API.jl:171
 [17] top-level scope
    @ none:1
```

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/Pkg.jl/issues/2925

**Pull request merged**
