### PR TITLE
Preserve the host environment during container set-up.

### PR DESCRIPTION
**Pull request by maleadt**
I'm trying to use some additional functionality during container set-up, but that's severely hampered by the environment being emptied _before_ executing the `sandbox` binary. Instead, let's preserve the host environment and only switch to a minimal container environment when calling `exec`.

For more details: `nvidia-container-cli` inspects `PATH` to find host binaries like `nvidia-smi` to mount those in the container.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@staticfloat Can you remind me of the process here? Do we first merge this PR, and then make a new Yggdrasil build? Or do we first make the new Yggdrasil build, and then re-run CI on this PR?

**Comment by staticfloat** [comment]
I'm not sure why you have a separate way of setting the environment... you should just set the environment for the `sandbox` process directly.  There are two ways to do this:

* You can set a default environment for all commands run by filling out the `env` member of the `SandboxConfig`:

```julia
using Sandbox
config = SandboxConfig(
    Dict("/" => Sandbox.alpine_rootfs()),
    Dict{String,String}(),
    Dict(ENV);
)
with_executor() do exe
    run(exe, config, `/bin/sh -c "set"`)
end
```

* You can use `addenv()`/`setenv()` on the `Cmd` object that you pass to `run` as well:

```julia
using Sandbox
config = SandboxConfig(
    Dict("/" => Sandbox.alpine_rootfs()),
)
with_executor() do exe
    run(exe, config, setenv(`/bin/sh -c "set"`, ENV))
end
```

I did waffle a bit on whether the default behavior should be to inherit `ENV` or not, and I eventually decided to err on the side of isolation.  But you still have the option to use as much of the host environment as you want!

**Comment by maleadt** [comment]
I don't think we're on the same line here. There *are* two environments at play:
- the host environment
- the sandbox environment

Currently, Sandbox.jl doesn't forward the host environment to the sandbox, and as you show there's two ways of forwarding parts of the host environment or otherwise setting environment variables for the sandbox. That's not what I'm interested in. I want the sandbox process to have access to the full host environment, while still being able to use an isolated sandbox environment (not forwarding ENV is totally fine), or to set specific values. That means there needs to be a separate way of setting the environment, because the host PATH I want the sandbox process to have access to may be different from the PATH I want to set _within_ the sandbox.

**Comment by maleadt** [comment]
PkgEval is not using Sandbox.jl anymore.

**Pull request closed without merging**
