### PR TITLE
Fix sysfs mount.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes https://github.com/staticfloat/Sandbox.jl/issues/98, supersedes https://github.com/staticfloat/Sandbox.jl/pull/97.

### CODE REVIEW

**Comment by maleadt** [comment]
FWIW, keeping the remount, adding MS_REC but dropping MS_NODEV (as suggested in https://github.com/staticfloat/Sandbox.jl/pull/97) didn't work.

**Comment by maleadt** [comment]
Okay, this doesn't work, guess the remount is required: https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/commit/?id=9ac77b8a78452eab0612523d27fee52159f5016a

**Comment by maleadt** [comment]
DockerExecutor failures with the nested test unrelated, and also happen on v1.3.0: https://github.com/staticfloat/Sandbox.jl/pull/100. So this should be good to go, I think.

**Comment by staticfloat** [comment]
The inner child of nesting can only really ever work with an unprivileged user namespace executor.  Previously, the nesting test that uses docker would use the DockerExecutor on the outside, but the unprivileged usernamespace executor on the inside. Looking at the build logs, it seems that the UnprivilegedUserNamespaceExecutor was completely broken on the CI machine, so those tests were all getting skipped.  I've since taken a look, and it appears this is because there are some inaccessible mount points listed in the kernel's list of mounts.  I've pushed a commit that works locally, let's see if it works on CI.

**Comment by staticfloat** [comment]
Looks good!

**Comment by maleadt** [comment]
Great! Care to tag a new version, or do you want to have this on master for a while?

**Comment by staticfloat** [comment]
I'm going to tag a new version once I can successfully deploy the new JLL to some of our buildbots.  I've run into a few issues (such as not having a valid `/etc/mtab`) that I'm ironing out. :)

**Pull request merged**
